openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore
  description: A sample API that uses a petstore as an example to demonstrate features
    in the OpenAPI 3.0 specification
servers:
  - url: http://petstore.swagger.io/api
paths:
  "/pets":
    get:
      description: |
        Returns all pets from the system
      operationId: findPets
      parameters:
        name: tags
        in: query
        description: tags to filter by
        required: false
        style: form
        schema:
          type: array
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
