openapi: 3.0.1
info:
  title: Test spec
  version: "1.1"
  x-api-audience: internal
paths:
  /operation11:
    post:
      operationId: operation11
  /operation12:
    post:
      operationId: operation12
  /operation13:
    post:
      operationId: operation13
