# @APIHUB_HOST = https://apihub-api-hub-dev-fe.k8s-apps3.k8s.sdntest.netcracker.com/
@APIHUB_HOST = http://localhost:8081/
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6InNlY3JldC1pZCIsInR5cCI6IkpXVCJ9.eyJFeHRlbnNpb25zIjp7ImdpdEludGVncmF0aW9uIjpbImZhbHNlIl0sInN5c3RlbVJvbGUiOlsiU3lzdGVtIGFkbWluaXN0cmF0b3IiXX0sIkdyb3VwcyI6W10sIklEIjoiYXBpaHViIiwiTmFtZSI6ImFwaWh1YiIsImF1ZCI6WyIiXSwiZXhwIjoxNzM5NTYwODUxLCJpYXQiOjE3Mzk1MTc2NTEsIm5iZiI6MTczOTUxNzY1MSwic3ViIjoiYXBpaHViIn0.QOaMmpdIAcXTLfWluBCyJDs3UiZ95EroWD1sAopWkkzWYvaL_qQFf_2GhW4b2O0E0Dr3qQopdu9_MkAOf9NOi6lY5ovcrft83mpQ8Ay7bE8DpDsO9hc1Hxfe7DmJ7LItJN55xfI305sRKE1NgQgVKLxB9hS6qeQrOBISvs8yLXI0EQ9ZRw0wONe8VXANy0mKW5oelSvcR8fS2toS1EowJESoSnfbT283ntuoSzKzbCXerMlffdBK1iEgkY6gqrpHwLc2l6YI_qObaU_ZBvvZRfrZmqtAJ9-b24sAWmSdYCT5ejkrHi1YoG4QY8Ss3LavxH-wTRpuoe_cS0hmzLQTZg

### Set system role
POST {{APIHUB_HOST}}/api/internal/users/{{userId}}/systemRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "role": "System administrator"
}

### Generate new apiKey
POST {{APIHUB_HOST}}/api/v2/packages/*/apiKeys
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "new_token"
}
