name: ESLint and Dprint checks

on:
  push:
    branches:
      - release
      - hotfix
      - develop
      - feature/*
      - bugfix/*
    tags:
      - "**"
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "docs/**"

jobs:
  eslint-dprint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com/"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ESLint check
        continue-on-error: true
        run: npm lint

      - name: Run Dprint check
        uses: dprint/check@v2.2
