name: Run screenshot tests

on:
  push

jobs:
  screenshot-tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.51.0-noble
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # This step is to update internal dependencies specified via tag version to their latest available versions
      - name: Update dependencies
        run: npm ls --json |  jq -r '.dependencies | keys[]' | grep "@netcracker" | xargs --no-run-if-empty npm update
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        id: tests
        continue-on-error: true
        run: npm run screenshot-test:ci

      - name: Upload differences
        if: steps.tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: packages/shared/src/it/playwright/playwright-report
          if-no-files-found: ignore
          retention-days: 14

      - name: Check test results
        if: steps.tests.outcome == 'failure'
        run: exit 1